project_id = "ehrxpaxvyuwiwqclqkyh"

[functions.grant-manual-access]
verify_jwt = false

[functions.get-users-for-admin]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.validate-discount]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.validate-document]
verify_jwt = true

[functions.support-chat]
verify_jwt = false

[functions.send-nurture-campaign]
verify_jwt = false
