project_id = "ehrxpaxvyuwiwqclqkyh"

[functions.create-payment]
verify_jwt = false

[functions.validate-discount]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.validate-document]
verify_jwt = true
